config/routes.rb
Importantevent::Application.routes.draw do
  resources :eventtrackers

  root :to => 'eventtrackers#index'

end

app/models/eventtracker.rb
class Eventtracker < ActiveRecord::Base
  attr_accessible :date, :description, :title
  default_scope :order => "date DESC"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/eventtrackers_controller.rb
class EventtrackersController < ApplicationController
  # GET /eventtrackers
  # GET /eventtrackers.json
  def index
    #@eventtrackers = Eventtracker.all
    @eventtrackers = Eventtracker.where('eventtrackers.date >= ?', Date.today)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eventtrackers }
    end
  end

  # GET /eventtrackers/1
  # GET /eventtrackers/1.json
  def show
    @eventtracker = Eventtracker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @eventtracker }
    end
  end

  # GET /eventtrackers/new
  # GET /eventtrackers/new.json
  def new
    @eventtracker = Eventtracker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @eventtracker }
    end
  end

  # GET /eventtrackers/1/edit
  def edit
    @eventtracker = Eventtracker.find(params[:id])
  end

  # POST /eventtrackers
  # POST /eventtrackers.json
  def create
    @eventtracker = Eventtracker.new(params[:eventtracker])

    respond_to do |format|
      if @eventtracker.save
        format.html { redirect_to @eventtracker, notice: 'Eventtracker was successfully created.' }
        format.json { render json: @eventtracker, status: :created, location: @eventtracker }
      else
        format.html { render action: "new" }
        format.json { render json: @eventtracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /eventtrackers/1
  # PUT /eventtrackers/1.json
  def update
    @eventtracker = Eventtracker.find(params[:id])

    respond_to do |format|
      if @eventtracker.update_attributes(params[:eventtracker])
        format.html { redirect_to @eventtracker, notice: 'Eventtracker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @eventtracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventtrackers/1
  # DELETE /eventtrackers/1.json
  def destroy
    @eventtracker = Eventtracker.find(params[:id])
    @eventtracker.destroy

    respond_to do |format|
      format.html { redirect_to eventtrackers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventtrackers_helper.rb
module EventtrackersHelper
end

app/views/eventtrackers/_form.html.erb
<%= form_for(@eventtracker) do |f| %>
  <% if @eventtracker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@eventtracker.errors.count, "error") %> prohibited this eventtracker from being saved:</h2>

      <ul>
      <% @eventtracker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventtrackers/edit.html.erb
<h1>Editing eventtracker</h1>

<%= render 'form' %>

<%= link_to 'Show', @eventtracker %> |
<%= link_to 'Back', eventtrackers_path %>

app/views/eventtrackers/index.html.erb
<%- model_class = Eventtracker -%>
<div class="page-header">
  <h1>Important Events/Dates</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>

<% @eventtrackers.each do |eventtracker| %>
  <tr>
    <td width="150"><%= eventtracker.title %></td>
    <td width="300"><%= eventtracker.description %></td>
    <td><%= eventtracker.date %></td>
    <td><%= link_to 'Show', eventtracker %></td>
    <td>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_eventtracker_path(eventtracker), :class => 'btn btn-mini' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  eventtracker_path(eventtracker),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-mini btn-danger' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_eventtracker_path,
            :class => 'btn btn-primary' %>

app/views/eventtrackers/new.html.erb
<h1>New eventtracker</h1>

<%= render 'form' %>

<%= link_to 'Back', eventtrackers_path %>

app/views/eventtrackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @eventtracker.title %>
</p>

<p>
  <b>Description:</b>
  <%= @eventtracker.description %>
</p>

<p>
  <b>Date:</b>
  <%= @eventtracker.date %>
</p>


<%= link_to 'Edit', edit_eventtracker_path(@eventtracker) %> |
<%= link_to 'Back', eventtrackers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Importantevent" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Importantevent</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "CodeFellows", "https://www.codefellows.org/"  %></li>
              <li><%= link_to "CF WOC July 2013", "https://canvas.instructure.com/courses/801977"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">About This App</li>
                This is a microapp that displays important events that I want to keep track of. The page shows the upcoming events only.
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>